
spring:
  datasource:
    url: jdbc:mysql://:3306/hotel?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: 
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 
    username: 
    password: 
    virtual-host: /
    port: 5672
    listener:
      simple:
        default-requeue-rejected: false
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo
