server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://43.139.46.197:3306/hotel?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: liubo9638@
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 43.139.46.197
    username: root
    password: root
    virtual-host: /
    port: 5672
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo